FIX: Aligment zero length sequence bug
eProsima/Micro-CDR pull request #54
Opened 2020-11-11 16:32 UTC by pablogs9

2020-11-11 16:37 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-CDR%20Manual%20Linux&build=12)](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Linux/12/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-CDR%20Manual%20Windows&build=11)](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Windows/11/)

2020-11-11 16:48 UTC, jamoralp requested changes

2020-11-11 16:48 UTC, jamoralp commented on test/serialization/SequenceSerialization.hpp
> +        EXPECT_EQ(output_size, (uint32_t) 0);
```suggestion
        EXPECT_EQ(output_size, static_cast<uint32_t>(0));
```

2020-11-11 16:48 UTC, jamoralp commented on test/serialization/SequenceSerialization.hpp
> +        EXPECT_EQ(readed, (uint32_t) 42);
```suggestion
        EXPECT_EQ(readed, static_cast<uint32_t>(42));
```

2020-11-12 11:10 UTC, pablogs9 commented on test/serialization/SequenceSerialization.hpp
> +        EXPECT_EQ(output_size, (uint32_t) 0);
Please check the new approach

2020-11-12 11:12 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-CDR%20Manual%20Linux&build=15)](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Linux/15/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-CDR%20Manual%20Windows&build=14)](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Windows/14/)

2020-11-12 11:18 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-CDR%20Manual%20Linux&build=16)](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Linux/16/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-CDR%20Manual%20Windows&build=15)](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Windows/15/)

2020-11-12 11:32 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-CDR%20Manual%20Linux&build=17)](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Linux/17/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-CDR%20Manual%20Windows&build=16)](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Windows/16/)

2020-11-12 11:38 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-CDR%20Manual%20Linux&build=18)](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Linux/18/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-CDR%20Manual%20Windows&build=17)](http://jenkins.eprosima.com:8080/job/Micro-CDR%20Manual%20Windows/17/)

2020-11-12 17:10 UTC, jamoralp approved these changes

2020-11-12 17:11 UTC, jamoralp commented
Looks good. We should take into consideration making a more complete test set (I.E. testing all basic types, creating custom complex types and test against uCDR-u-CDR, FastCDR-uCDR, uCDR-FastCDR).

2020-11-12 17:21 UTC, merged